Repository BeomSeogKim/Final-Project, pull requests merged in 2022-10, with the labels that each got.

#100 Enhance
  README.md
  appspec.yml
  scripts/health_check.sh
  scripts/run_new_was.sh
  src/main/java/Backend/FinalProject/controller/ReportController.java
  src/main/java/Backend/FinalProject/domain/Member.java
  src/main/java/Backend/FinalProject/domain/Report.java
  src/main/java/Backend/FinalProject/domain/enums/Gender.java
  src/main/java/Backend/FinalProject/dto/request/ReportDto.java
  src/main/java/Backend/FinalProject/dto/request/SignupRequestDto.java
  src/main/java/Backend/FinalProject/repository/ReportRepository.java
  src/main/java/Backend/FinalProject/service/MemberService.java
  src/main/java/Backend/FinalProject/service/OAuthService.java
  src/main/java/Backend/FinalProject/service/ReportService.java
Labels: enhancement

#101 Develop
  src/main/java/Backend/FinalProject/controller/ReportController.java
  src/main/java/Backend/FinalProject/domain/Member.java
  src/main/java/Backend/FinalProject/domain/Report.java
  src/main/java/Backend/FinalProject/domain/enums/Gender.java
  src/main/java/Backend/FinalProject/dto/KakaoUserInfoDto.java
  src/main/java/Backend/FinalProject/dto/request/ReportDto.java
  src/main/java/Backend/FinalProject/dto/request/SignupRequestDto.java
  src/main/java/Backend/FinalProject/repository/ReportRepository.java
  src/main/java/Backend/FinalProject/service/MemberService.java
  src/main/java/Backend/FinalProject/service/OAuthService.java
  src/main/java/Backend/FinalProject/service/ReportService.java
Labels: enhancement

#120 Entity
  src/main/java/Backend/FinalProject/FinalProjectApplication.java
  src/main/java/Backend/FinalProject/WebSocket/ChatRoomDto.java
  src/main/java/Backend/FinalProject/WebSocket/controller/ChatRoomController.java
  src/main/java/Backend/FinalProject/WebSocket/domain/ChatMember.java
  src/main/java/Backend/FinalProject/WebSocket/domain/ChatRoom.java
  src/main/java/Backend/FinalProject/WebSocket/domain/dtos/ChatMessageDto.java
  src/main/java/Backend/FinalProject/WebSocket/domain/dtos/ChatMessageInfoDto.java
  src/main/java/Backend/FinalProject/WebSocket/domain/dtos/ChatMessageResponse.java
  src/main/java/Backend/FinalProject/WebSocket/repository/ChatMessageRepository.java
  src/main/java/Backend/FinalProject/WebSocket/service/ChatRoomService.java
  src/main/java/Backend/FinalProject/WebSocket/service/ChatService.java
  src/main/java/Backend/FinalProject/controller/MemberController.java
  src/main/java/Backend/FinalProject/controller/PostController.java
  src/main/java/Backend/FinalProject/domain/Application.java
  src/main/java/Backend/FinalProject/domain/Comment.java
  src/main/java/Backend/FinalProject/domain/Member.java
  src/main/java/Backend/FinalProject/domain/Post.java
  src/main/java/Backend/FinalProject/domain/WishList.java
  src/main/java/Backend/FinalProject/domain/enums/Category.java
  src/main/java/Backend/FinalProject/domain/enums/Regulation.java
  src/main/java/Backend/FinalProject/dto/request/PostRequestDto.java
  src/main/java/Backend/FinalProject/dto/response/PostResponseDtoPage.java
  src/main/java/Backend/FinalProject/repository/PostRepository.java
  src/main/java/Backend/FinalProject/service/CommentService.java
  src/main/java/Backend/FinalProject/service/MemberService.java
  src/main/java/Backend/FinalProject/service/OAuthService.java
  src/main/java/Backend/FinalProject/service/PostService.java
  src/main/resources/application.properties
Labels: enhancement

#129 Enhance
  src/main/java/Backend/FinalProject/Tool/SchedulerService.java
  src/main/java/Backend/FinalProject/domain/Member.java
  src/main/java/Backend/FinalProject/domain/Post.java
  src/main/java/Backend/FinalProject/domain/SignOutMember.java
  src/main/java/Backend/FinalProject/repository/SignOutRepository.java
  src/main/java/Backend/FinalProject/service/MemberService.java
Labels: enhancement

#144 신고목록 조회할때 값 추가
  src/main/java/Backend/FinalProject/dto/response/report/ReportCommentDto.java
  src/main/java/Backend/FinalProject/dto/response/report/ReportMemberDto.java
  src/main/java/Backend/FinalProject/dto/response/report/ReportPostDto.java
  src/main/java/Backend/FinalProject/service/AdminService.java
Labels: enhancement

#146 시큐리티 설정 변경
  src/main/java/Backend/FinalProject/configuration/SecurityConfiguration.java
  src/main/resources/application.properties
Labels: bug

#148 상세게시글 조회 권한 변경
  src/main/java/Backend/FinalProject/configuration/SecurityConfiguration.java
Labels: enhancement

#149 Develop
  src/main/java/Backend/FinalProject/WebSocket/controller/ChatRoomController.java
  src/main/java/Backend/FinalProject/WebSocket/domain/ChatMemberResponseDto.java
  src/main/java/Backend/FinalProject/WebSocket/repository/ChatMemberRepository.java
  src/main/java/Backend/FinalProject/WebSocket/repository/ChatRoomRepository.java
  src/main/java/Backend/FinalProject/WebSocket/service/ChatRoomService.java
  src/main/java/Backend/FinalProject/dto/PostResponseDto.java
  src/main/java/Backend/FinalProject/service/AdminService.java
  src/main/java/Backend/FinalProject/service/PostService.java
Labels: enhancement

#151 게시글 마감 조건 변경 및 스케쥴러 변경 # 150
  src/main/java/Backend/FinalProject/Tool/SchedulerService.java
  src/main/java/Backend/FinalProject/controller/ApplicationController.java
  src/main/java/Backend/FinalProject/domain/Post.java
  src/main/java/Backend/FinalProject/service/ApplicationService.java
Labels: enhancement

#152 Develop
  src/main/java/Backend/FinalProject/Tool/SchedulerService.java
  src/main/java/Backend/FinalProject/controller/ApplicationController.java
  src/main/java/Backend/FinalProject/domain/Post.java
  src/main/java/Backend/FinalProject/service/ApplicationService.java
Labels: enhancement

#155 Querydsl
  build.gradle
  src/main/java/Backend/FinalProject/controller/PostController.java
  src/main/java/Backend/FinalProject/dto/SearchDto.java
  src/main/java/Backend/FinalProject/service/PostService.java
Labels: enhancement

#157 Pagenation 구현 및 전체 카테고리 로직 추가 #154
  src/main/java/Backend/FinalProject/controller/PostController.java
  src/main/java/Backend/FinalProject/service/PostService.java
Labels: bug, enhancement

#167 Re issue
  build.gradle
  src/main/java/Backend/FinalProject/configuration/SecurityConfiguration.java
  src/main/java/Backend/FinalProject/controller/MemberController.java
  src/main/java/Backend/FinalProject/domain/RefreshToken.java
  src/main/java/Backend/FinalProject/sercurity/TokenProvider.java
  src/main/java/Backend/FinalProject/service/MemberService.java
Labels: enhancement

#170 알림에 이동할 주소 추가 #162
  src/main/java/Backend/FinalProject/service/ApplicationService.java
  src/main/java/Backend/FinalProject/service/CommentService.java
  src/main/java/Backend/FinalProject/sse/controller/NotificationController.java
  src/main/java/Backend/FinalProject/sse/domain/Notification.java
  src/main/java/Backend/FinalProject/sse/domain/RelatedUrl.java
  src/main/java/Backend/FinalProject/sse/service/NotificationService.java
  src/main/resources/static/index.html
Labels: enhancement

#169 알림에 이동할 주소 추가 #162
  src/main/java/Backend/FinalProject/service/ApplicationService.java
  src/main/java/Backend/FinalProject/service/CommentService.java
  src/main/java/Backend/FinalProject/sse/controller/NotificationController.java
  src/main/java/Backend/FinalProject/sse/domain/Notification.java
  src/main/java/Backend/FinalProject/sse/domain/RelatedUrl.java
  src/main/java/Backend/FinalProject/sse/service/NotificationService.java
  src/main/resources/static/index.html
Labels: enhancement

#172 토큰 로직 1차 변경 #160
  src/main/java/Backend/FinalProject/configuration/SecurityConfiguration.java
  src/main/java/Backend/FinalProject/controller/TestController.java
Labels: enhancement

#173 Develop
  README.md
  src/main/java/Backend/FinalProject/configuration/SecurityConfiguration.java
  src/main/java/Backend/FinalProject/controller/TestController.java
  src/main/java/Backend/FinalProject/sse/service/NotificationService.java
Labels: bug, enhancement

#177 HikariPoolSize 변경 및 OSIV 설정 변경 #160
  src/main/resources/application.properties
Labels: enhancement, new task

#184 Controller Refactoring #113
  src/main/java/Backend/FinalProject/WebSocket/controller/ChatController.java
  src/main/java/Backend/FinalProject/WebSocket/controller/ChatRoomController.java
  src/main/java/Backend/FinalProject/WebSocket/service/ChatRoomService.java
  src/main/java/Backend/FinalProject/controller/AdminController.java
  src/main/java/Backend/FinalProject/controller/ApplicationController.java
  src/main/java/Backend/FinalProject/controller/CommentController.java
  src/main/java/Backend/FinalProject/controller/MemberController.java
  src/main/java/Backend/FinalProject/controller/MyActController.java
  src/main/java/Backend/FinalProject/controller/MyPageController.java
  src/main/java/Backend/FinalProject/controller/OAuthController.java
  src/main/java/Backend/FinalProject/controller/PostController.java
  src/main/java/Backend/FinalProject/controller/ReportController.java
  src/main/java/Backend/FinalProject/controller/TestController.java
  src/main/java/Backend/FinalProject/service/CommentService.java
  src/main/java/Backend/FinalProject/service/MemberService.java
  src/main/java/Backend/FinalProject/service/MyActService.java
  src/main/java/Backend/FinalProject/service/MyPageService.java
  src/main/java/Backend/FinalProject/service/PostService.java
Labels: enhancement

#187 Develop
  src/main/java/Backend/FinalProject/FinalProjectApplication.java
  src/main/java/Backend/FinalProject/Tool/Validation.java
  src/main/java/Backend/FinalProject/WebSocket/service/ChatRoomService.java
  src/main/java/Backend/FinalProject/WebSocket/service/ChatService.java
  src/main/java/Backend/FinalProject/domain/enums/ErrorCode.java
  src/main/java/Backend/FinalProject/domain/enums/baseImage.java
  src/main/java/Backend/FinalProject/repository/PostRepository.java
  src/main/java/Backend/FinalProject/service/ApplicationService.java
  src/main/java/Backend/FinalProject/service/PostService.java
Labels: enhancement

#208 안읽은 채팅 확인 API 개발
  src/main/java/Backend/FinalProject/WebSocket/controller/ChatRoomController.java
  src/main/java/Backend/FinalProject/WebSocket/repository/ChatMessageRepository.java
  src/main/java/Backend/FinalProject/WebSocket/repository/ChatRoomRepository.java
  src/main/java/Backend/FinalProject/sse/controller/NotificationController.java
  src/main/java/Backend/FinalProject/sse/dto/NotificationChatCountDto.java
  src/main/java/Backend/FinalProject/sse/service/NotificationService.java
Labels: enhancement

#215 Develop
  src/main/java/Backend/FinalProject/WebSocket/controller/ChatRoomController.java
  src/main/java/Backend/FinalProject/WebSocket/service/ChatRoomService.java
  src/main/java/Backend/FinalProject/WebSocket/service/ChatService.java
  src/main/java/Backend/FinalProject/repository/PostRepository.java
  src/main/java/Backend/FinalProject/service/PostService.java
  src/main/java/Backend/FinalProject/sse/repository/NotificationRepository.java
Labels: bug, enhancement

#223 채팅방 로직 변경 #45
  src/main/java/Backend/FinalProject/WebSocket/service/ChatService.java
Labels: bug, enhancement

#238 Develop
  scripts/run_new_was.sh
  src/main/java/Backend/FinalProject/FinalProjectApplication.java
  src/main/java/Backend/FinalProject/configuration/SecurityConfiguration.java
  src/main/java/Backend/FinalProject/controller/MemberController.java
  src/main/java/Backend/FinalProject/domain/enums/ErrorCode.java
  src/main/java/Backend/FinalProject/service/MemberService.java
  src/main/java/Backend/FinalProject/service/OAuthService.java
  src/main/java/Backend/FinalProject/service/PostService.java
Labels: bug, documentation, enhancement
